apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "docker-registry-browser.fullname" . }}
  labels:
    {{- include "docker-registry-browser.labels" . | nindent 4 }}
data:
  {{/*
    Rather than maintain a comprehensive ConfigMap, we map all sub-keys of the "env" value here.
  */}}
{{- range $envKey, $envVal := .Values.env }}
  {{ $envKey | upper }}: {{ $envVal | quote }}
{{- end }}
